# Generated by Django 4.2.4 on 2023-08-30 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyhub', '0003_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveIntegerField(verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Карта'), ('cash', 'Наличными')], default='transfer', verbose_name='Метод платежа'),
        ),
    ]
